name: Docker test Image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: node:slim

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile.dev --tag test-image
    - name: Run tests
      run: docker run -e CI=true test-image npm run test -- --coverage
    
