name: Docker test Image

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      env:
        DOCKER_HUB_SECRET: ${{ secrets.YOLZIII_DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: Docker login
        run: docker login --username yolziii --password $DOCKER_HUB_SECRET
      - name: Build the Docker image
        run: docker build . --file Dockerfile.dev --tag test-image
      - name: Run tests
        run: docker run -e CI=true test-image npm run test -- --coverage
